### ISSUE TITLE
Close button and thumbnails size

### ISSUE THREAD

**Issue by f4bpp** [Cobinja/CobiWindowList#2]
Hi !

First, many thanks for the work. Your app is better than Icing Task Manager because I now have only thumbnail preview for each wine app while I get two with ITM.

But unlike the screenshot of the App in cinnamon spices, there is no close button on the thumbnails and there is no way to change the size of them.

My config is : Linux Mint 18.1 64 bits with Cinnamon 3.2.7

Thanks to sole the issues.

David.

**Comment by Cobinja** [comment]
The close button is only visible when hovering the thumbnail.
Which cinnamon theme do you use? It could be one that doesn't have an icon for that.
Size management for the thumbnails is not yet included, but will probably come in a future version

**Comment by Cobinja** [comment]
The close button is only visible when hovering the thumbnail.
Which cinnamon theme do you use? It could be one that doesn't have an icon for that. you can check by entering Expo (the overview of workspaces). If the workspaces there have a close icon in the top right corner when hovering them, it should work in this applet too. Otherwise it's a theme issue.
Size management for the thumbnails is not yet included, but will probably come in a future version

**Comment by Cobinja** [comment]
The close button is only visible when hovering the thumbnail.
Which cinnamon theme do you use? It could be one that doesn't have an icon for that. you can check by entering Expo (the overview of workspaces). If the workspaces there have a close icon in the top right corner when hovering them, it should work in this applet too. Otherwise it's a theme issue.

Size management for the thumbnails is not yet included, but will probably come in a future version.

**Comment by Cobinja** [comment]
The close button is only visible when hovering the thumbnail.
Which cinnamon theme do you use? It could be one that doesn't have an icon for that. You can check by entering Expo (the overview of workspaces). If the workspaces there have a close icon in the top right corner when hovering them, it should work in this applet too. Otherwise it's a theme issue.

Size management for the thumbnails is not yet included, but will probably come in a future version.

**Comment by f4bpp** [comment]
Ok you're right. This is a problem with the theme I use but I can't use another one since it is the only one for having a working Windows 7 look and since my job is sometimes to recycle old PC to slow for windows into Linux, I have to deal with.

There is many things I've modified to make it work but I don't know what I have to change to enable the close button on it. Icing Task Manager deals well with it. So here is a copy of the theme I've called "Mint-X-Aero". If you can do something so that it shows the close button, I would appreciate.

Thanks for your help.
[Mint-X-Aero.zip](https://github.com/Cobinja/CobiWindowList/files/1256520/Mint-X-Aero.zip)

**Comment by Cobinja** [comment]
Sorry, but I will not fix your theme for you. If you modified it, it's you who should fix it.
Hint: Take a look at how other themes handle the css class "window-close".
