### ISSUE TITLE
Close windows by middle click on panel icon

### ISSUE THREAD

**Issue by Mgldvd** [Cobinja/CobiWindowList#24]
Great App! Thanks
The only option i miss is to close windows by middle click on icon 
Thanks again

**Comment by markkrj** [comment]
You can close by middle clicking the preview. I think it's great having the ability to open new instance of and application by middle clicking its icon and when having multiple windows open, I can middle click the preview to close it. Maybe it could have an option in settings to alternate between those behaviors.

**Comment by Cobinja** [comment]
Closed because of #28

**Comment by igorsantos07** [comment]
Nice, so the feature request got shunned because "no" and also because "Windows does it differently", even though all other similar DEs on Linux close the window on middle-click. And last but not least, you wasted a contributor's time asking for them to implement extra stuff, only to state "actually, no, I don't like the main idea in the first place".

Definitely the best way to go.

For anyone else ending up here looking for why the heck the middle-button doesn't close a window, check [Cassia](https://cinnamon-spices.linuxmint.com/applets/view/372) instead. It's a better-done fork of this project.
